version: '3'
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=datajdbc
      - POSTGRES_USER=datajdbc
      - POSTGRES_PASSWORD=datajdbc
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
